export const FORUM_CATEGORIES = [
  "Technology",
  "Gaming",
  "Science",
  "Art & Design",
  "Music",
  "Movies & TV",
  "Books & Literature",
  "Sports",
  "Health & Fitness",
  "Food & Cooking",
  "Travel",
  "Photography",
  "Business",
  "Education",
  "Politics",
  "News",
  "Lifestyle",
  "Fashion",
  "DIY & Crafts",
  "Pets & Animals",
  "Automotive",
  "Real Estate",
  "Finance",
  "Cryptocurrency",
  "Programming",
  "Web Development",
  "Mobile Apps",
  "AI & Machine Learning",
  "Cybersecurity",
  "General Discussion",
] as const

export type ForumCategory = (typeof FORUM_CATEGORIES)[number]
